import { Test } from '@nestjs/testing';
import { PlaylistService } from '../src/modules/playlist/playlist.service';
import { SpotifyService } from '../src/modules/spotify/spotify.service';
import { DataEngineService } from '../src/modules/data-engine/data-engine.service';
import { SongService } from '../src/modules/song/song.service';

describe('PlaylistService', () => {
  let service: PlaylistService;
  let spotifyService: jest.Mocked<SpotifyService>;
  let dataEngineService: jest.Mocked<DataEngineService>;
  let songService: jest.Mocked<SongService>;

  beforeEach(async () => {
    const module = await Test.createTestingModule({
      providers: [
        PlaylistService,
        {
          provide: SpotifyService,
          useValue: {
            getTopTracks: jest.fn(),
            searchTrackDetails: jest.fn(),
            createPlaylist: jest.fn(),
            addTracksToPlaylist: jest.fn(),
          },
        },
        {
          provide: DataEngineService,
          useValue: {
            getRecommendations: jest.fn(),
            ingestBatch: jest.fn(),
          },
        },
        {
          provide: SongService,
          useValue: {
            upsertSongsFromTracks: jest.fn(),
            updateEmbeddings: jest.fn(),
          },
        },
      ],
    }).compile();

    module.useLogger(false);

    service = module.get(PlaylistService);
    spotifyService = module.get(SpotifyService);
    dataEngineService = module.get(DataEngineService);
    songService = module.get(SongService);

    spotifyService.getTopTracks.mockResolvedValue([{ title: 'Mock Top', artist: 'Mock Artist' }]);
    dataEngineService.ingestBatch.mockResolvedValue([]);
    songService.updateEmbeddings.mockResolvedValue(undefined);
  });

  const spotifyTrack = (id: string, title = `Song ${id}`, artist = `Artist ${id}`) => ({
    id,
    uri: `spotify:track:${id}`,
    title,
    artist,
    url: `https://open.spotify.com/track/${id}`,
  });

  const savedSong = (id: string, name = `Song ${id}`, artistName = `Artist ${id}`, embedding: string | null = '[0.1,0.2]') => ({
    id: `song-${id}`,
    name,
    artistName,
    spotifyUri: `spotify:track:${id}`,
    embedding,
    createdAt: new Date(),
  });

  it('should create a playlist end-to-end', async () => {
    spotifyService.getTopTracks.mockResolvedValue([{ title: 'Top', artist: 'Artist' }]);
    dataEngineService.getRecommendations.mockResolvedValue([
      { title: 'Song A', artist: 'Artist A', is_new: false },
      { title: 'Song B', artist: 'Artist B', is_new: true },
    ]);
    spotifyService.searchTrackDetails
      .mockResolvedValueOnce(spotifyTrack('aaa', 'Song A', 'Artist A'))
      .mockResolvedValueOnce(spotifyTrack('bbb', 'Song B', 'Artist B'));
    songService.upsertSongsFromTracks.mockResolvedValue([
      savedSong('aaa', 'Song A', 'Artist A'),
      savedSong('bbb', 'Song B', 'Artist B'),
    ]);
    spotifyService.createPlaylist.mockResolvedValue({
      id: 'playlist789',
      url: 'https://open.spotify.com/playlist/playlist789',
    });
    spotifyService.addTracksToPlaylist.mockResolvedValue(undefined);

    const result = await service.generatePlaylist('token', {
      eventDescription: 'Chill evening',
    });

    expect(result).toEqual({
      playlistId: 'playlist789',
      playlistUrl: 'https://open.spotify.com/playlist/playlist789',
      tracksAdded: 2,
      tracksNotFound: [],
      totalRequested: 2,
      tracks: [
        {
          songId: 'song-aaa',
          title: 'Song A',
          artist: 'Artist A',
          spotifyUri: 'spotify:track:aaa',
          spotifyUrl: 'https://open.spotify.com/track/aaa',
          position: 1,
        },
        {
          songId: 'song-bbb',
          title: 'Song B',
          artist: 'Artist B',
          spotifyUri: 'spotify:track:bbb',
          spotifyUrl: 'https://open.spotify.com/track/bbb',
          position: 2,
        },
      ],
    });
    expect(spotifyService.createPlaylist).toHaveBeenCalledWith(
      'token', 'JamOn: Chill evening', true, 'Generated by JamOn for: Chill evening',
    );
    expect(spotifyService.addTracksToPlaylist).toHaveBeenCalledWith(
      'token', 'playlist789', ['spotify:track:aaa', 'spotify:track:bbb'],
    );
  });

  it('should skip tracks not found on Spotify', async () => {
    dataEngineService.getRecommendations.mockResolvedValue([
      { title: 'Found Song', artist: 'Artist', is_new: false },
      { title: 'Missing Song', artist: 'Nobody', is_new: true },
    ]);
    spotifyService.searchTrackDetails
      .mockResolvedValueOnce(spotifyTrack('found', 'Found Song', 'Artist'))
      .mockResolvedValueOnce(null);
    songService.upsertSongsFromTracks.mockResolvedValue([
      savedSong('found', 'Found Song', 'Artist'),
    ]);
    spotifyService.createPlaylist.mockResolvedValue({
      id: 'pl1', url: 'https://open.spotify.com/playlist/pl1',
    });
    spotifyService.addTracksToPlaylist.mockResolvedValue(undefined);

    const result = await service.generatePlaylist('token', {
      eventDescription: 'Test event',
    });

    expect(result.tracksAdded).toBe(1);
    expect(result.tracksNotFound).toEqual(['Missing Song by Nobody']);
    expect(spotifyService.addTracksToPlaylist).toHaveBeenCalledWith(
      'token', 'pl1', ['spotify:track:found'],
    );
  });

  it('should throw NO_TRACKS_RESOLVED when no tracks are found on Spotify', async () => {
    dataEngineService.getRecommendations.mockResolvedValue([
      { title: 'Missing', artist: 'Nobody', is_new: true },
    ]);
    spotifyService.searchTrackDetails.mockResolvedValue(null);

    try {
      await service.generatePlaylist('token', { eventDescription: 'Test' });
      fail('Expected HttpException');
    } catch (e: any) {
      expect(e.getResponse().error).toBe('NO_TRACKS_RESOLVED');
    }
  });

  it('should throw NO_TRACKS_RESOLVED when data engine returns empty', async () => {
    dataEngineService.getRecommendations.mockResolvedValue([]);

    try {
      await service.generatePlaylist('token', { eventDescription: 'Test' });
      fail('Expected HttpException');
    } catch (e: any) {
      expect(e.getResponse().error).toBe('NO_TRACKS_RESOLVED');
    }
  });

  it('should propagate Spotify 401 errors', async () => {
    dataEngineService.getRecommendations.mockResolvedValue([
      { title: 'Song', artist: 'Artist', is_new: false },
    ]);
    spotifyService.searchTrackDetails.mockRejectedValue({
      response: { status: 401, data: { error: { message: 'The access token expired' } } },
    });

    await expect(
      service.generatePlaylist('bad-token', { eventDescription: 'Test' }),
    ).rejects.toBeDefined();
  });

  it('should throw when playlist creation fails', async () => {
    dataEngineService.getRecommendations.mockResolvedValue([
      { title: 'Song', artist: 'Artist', is_new: false },
    ]);
    spotifyService.searchTrackDetails.mockResolvedValue(spotifyTrack('x', 'Song', 'Artist'));
    songService.upsertSongsFromTracks.mockResolvedValue([
      savedSong('x', 'Song', 'Artist'),
    ]);
    spotifyService.createPlaylist.mockRejectedValue(new Error('Spotify API error'));

    await expect(
      service.generatePlaylist('token', { eventDescription: 'Test' }),
    ).rejects.toThrow('Spotify API error');
  });

  it('should use custom playlist name when provided', async () => {
    dataEngineService.getRecommendations.mockResolvedValue([
      { title: 'Song', artist: 'Artist', is_new: false },
    ]);
    spotifyService.searchTrackDetails.mockResolvedValue(spotifyTrack('x', 'Song', 'Artist'));
    songService.upsertSongsFromTracks.mockResolvedValue([
      savedSong('x', 'Song', 'Artist'),
    ]);
    spotifyService.createPlaylist.mockResolvedValue({ id: 'p', url: 'https://open.spotify.com/playlist/p' });
    spotifyService.addTracksToPlaylist.mockResolvedValue(undefined);

    await service.generatePlaylist('token', {
      eventDescription: 'Party',
      playlistName: 'My Custom Name',
    });

    expect(spotifyService.createPlaylist).toHaveBeenCalledWith(
      'token', 'My Custom Name', true, 'Generated by JamOn for: Party',
    );
  });
});
