"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const testing_1 = require("@nestjs/testing");
const playlist_service_1 = require("../src/modules/playlist/playlist.service");
const spotify_service_1 = require("../src/modules/spotify/spotify.service");
const data_engine_service_1 = require("../src/modules/data-engine/data-engine.service");
describe('PlaylistService', () => {
    let service;
    let spotifyService;
    let dataEngineService;
    beforeEach(async () => {
        const module = await testing_1.Test.createTestingModule({
            providers: [
                playlist_service_1.PlaylistService,
                {
                    provide: spotify_service_1.SpotifyService,
                    useValue: {
                        searchTrack: jest.fn(),
                        createPlaylist: jest.fn(),
                        addTracksToPlaylist: jest.fn(),
                    },
                },
                {
                    provide: data_engine_service_1.DataEngineService,
                    useValue: {
                        getRecommendations: jest.fn(),
                    },
                },
            ],
        }).compile();
        module.useLogger(false);
        service = module.get(playlist_service_1.PlaylistService);
        spotifyService = module.get(spotify_service_1.SpotifyService);
        dataEngineService = module.get(data_engine_service_1.DataEngineService);
    });
    it('should create a playlist end-to-end', async () => {
        dataEngineService.getRecommendations.mockResolvedValue([
            { title: 'Song A', artist: 'Artist A', is_new: false },
            { title: 'Song B', artist: 'Artist B', is_new: true },
        ]);
        spotifyService.searchTrack
            .mockResolvedValueOnce('spotify:track:aaa')
            .mockResolvedValueOnce('spotify:track:bbb');
        spotifyService.createPlaylist.mockResolvedValue({
            id: 'playlist789',
            url: 'https://open.spotify.com/playlist/playlist789',
        });
        spotifyService.addTracksToPlaylist.mockResolvedValue(undefined);
        const result = await service.generatePlaylist('token', {
            eventDescription: 'Chill evening',
        });
        expect(result).toEqual({
            playlistId: 'playlist789',
            playlistUrl: 'https://open.spotify.com/playlist/playlist789',
            tracksAdded: 2,
            tracksNotFound: [],
            totalRequested: 2,
        });
        expect(spotifyService.createPlaylist).toHaveBeenCalledWith('token', 'JamOn: Chill evening', true, 'Generated by JamOn for: Chill evening');
        expect(spotifyService.addTracksToPlaylist).toHaveBeenCalledWith('token', 'playlist789', ['spotify:track:aaa', 'spotify:track:bbb']);
    });
    it('should skip tracks not found on Spotify', async () => {
        dataEngineService.getRecommendations.mockResolvedValue([
            { title: 'Found Song', artist: 'Artist', is_new: false },
            { title: 'Missing Song', artist: 'Nobody', is_new: true },
        ]);
        spotifyService.searchTrack
            .mockResolvedValueOnce('spotify:track:found')
            .mockResolvedValueOnce(null);
        spotifyService.createPlaylist.mockResolvedValue({
            id: 'pl1', url: 'https://open.spotify.com/playlist/pl1',
        });
        spotifyService.addTracksToPlaylist.mockResolvedValue(undefined);
        const result = await service.generatePlaylist('token', {
            eventDescription: 'Test event',
        });
        expect(result.tracksAdded).toBe(1);
        expect(result.tracksNotFound).toEqual(['Missing Song by Nobody']);
        expect(spotifyService.addTracksToPlaylist).toHaveBeenCalledWith('token', 'pl1', ['spotify:track:found']);
    });
    it('should throw NO_TRACKS_RESOLVED when no tracks are found on Spotify', async () => {
        dataEngineService.getRecommendations.mockResolvedValue([
            { title: 'Missing', artist: 'Nobody', is_new: true },
        ]);
        spotifyService.searchTrack.mockResolvedValue(null);
        try {
            await service.generatePlaylist('token', { eventDescription: 'Test' });
            fail('Expected HttpException');
        }
        catch (e) {
            expect(e.getResponse().error).toBe('NO_TRACKS_RESOLVED');
        }
    });
    it('should throw NO_TRACKS_RESOLVED when data engine returns empty', async () => {
        dataEngineService.getRecommendations.mockResolvedValue([]);
        try {
            await service.generatePlaylist('token', { eventDescription: 'Test' });
            fail('Expected HttpException');
        }
        catch (e) {
            expect(e.getResponse().error).toBe('NO_TRACKS_RESOLVED');
        }
    });
    it('should propagate Spotify 401 errors', async () => {
        dataEngineService.getRecommendations.mockResolvedValue([
            { title: 'Song', artist: 'Artist', is_new: false },
        ]);
        spotifyService.searchTrack.mockRejectedValue({
            response: { status: 401, data: { error: { message: 'The access token expired' } } },
        });
        await expect(service.generatePlaylist('bad-token', { eventDescription: 'Test' })).rejects.toBeDefined();
    });
    it('should throw when playlist creation fails', async () => {
        dataEngineService.getRecommendations.mockResolvedValue([
            { title: 'Song', artist: 'Artist', is_new: false },
        ]);
        spotifyService.searchTrack.mockResolvedValue('spotify:track:x');
        spotifyService.createPlaylist.mockRejectedValue(new Error('Spotify API error'));
        await expect(service.generatePlaylist('token', { eventDescription: 'Test' })).rejects.toThrow('Spotify API error');
    });
    it('should use custom playlist name when provided', async () => {
        dataEngineService.getRecommendations.mockResolvedValue([
            { title: 'Song', artist: 'Artist', is_new: false },
        ]);
        spotifyService.searchTrack.mockResolvedValue('spotify:track:x');
        spotifyService.createPlaylist.mockResolvedValue({ id: 'p', url: 'https://open.spotify.com/playlist/p' });
        spotifyService.addTracksToPlaylist.mockResolvedValue(undefined);
        await service.generatePlaylist('token', {
            eventDescription: 'Party',
            playlistName: 'My Custom Name',
        });
        expect(spotifyService.createPlaylist).toHaveBeenCalledWith('token', 'My Custom Name', true, 'Generated by JamOn for: Party');
    });
});
//# sourceMappingURL=playlist.service.spec.js.map