from pydantic import BaseModel, Field
from typing import List, Dict, Any

class PlaylistState(BaseModel):
    event_description: str = Field(..., description="The user's description of the event")
    db_songs: List[Dict[str, Any]] = Field(default_factory=list, description="Songs retrieved from the database")
    anchor_artists: List[str] = Field(default_factory=list, description="Deduplicated artist list from db_songs for wildcard anchoring")
    candidate_wildcards: List[Dict[str, Any]] = Field(default_factory=list, description="Candidate songs generated by the LLM")
    validated_wildcards: List[Dict[str, Any]] = Field(default_factory=list, description="LLM songs that have been validated")
    rejected_wildcards: List[str] = Field(default_factory=list, description="Songs that failed validation")
    attempts: int = Field(default=0, description="Number of attempts to generate and validate songs")
    final_playlist: List[Dict[str, Any]] = Field(default_factory=list, description="The final combined and shuffled playlist")
