import { Injectable, Logger, HttpException, HttpStatus } from "@nestjs/common";
import { SpotifyService } from "../spotify/spotify.service";
import { DataEngineService } from "../data-engine/data-engine.service";
import { SongService } from "../song/song.service";
import { CreatePlaylistDto } from "./dto/create-playlist.dto";
import {
  PlaylistResponseDto,
  PlaylistError,
  PlaylistTrackResultDto,
} from "./dto/playlist-response.dto";
import { SpotifyTrackMatch } from "../spotify/spotify.types";

@Injectable()
export class PlaylistService {
  private readonly logger = new Logger(PlaylistService.name);

  constructor(
    private readonly spotifyService: SpotifyService,
    private readonly dataEngineService: DataEngineService,
    private readonly songService: SongService,
  ) {}

  async generatePlaylist(
    accessToken: string,
    dto: CreatePlaylistDto,
  ): Promise<PlaylistResponseDto> {
    this.logger.log(
      `[generatePlaylist] START — eventDescription="${dto.eventDescription}"`,
    );

    this.logger.log("[generatePlaylist] Fetching top tracks from Spotify...");
    const topTracks = await this.spotifyService.getTopTracks(accessToken, 30);
    this.logger.log(`[generatePlaylist] Got ${topTracks.length} top tracks`);

    this.logger.log("[generatePlaylist] Calling data-engine /recommend...");
    const songs = await this.dataEngineService.getRecommendations(
      dto.eventDescription,
      topTracks,
    );
    this.logger.log(
      `[generatePlaylist] Data-engine returned ${songs.length} recommendations`,
    );

    if (!songs.length) {
      throw new HttpException(
        {
          error: PlaylistError.NO_TRACKS_RESOLVED,
          message: "Data engine returned no recommendations",
        },
        HttpStatus.UNPROCESSABLE_ENTITY,
      );
    }

    // 2. Resolve each song to a Spotify URI (concurrency limit of 5)
    const resolvedTracks: SpotifyTrackMatch[] = [];
    const notFound: string[] = [];

    const chunks: (typeof songs)[] = [];
    for (let i = 0; i < songs.length; i += 5) {
      chunks.push(songs.slice(i, i + 5));
    }

    for (const chunk of chunks) {
      const results = await Promise.all(
        chunk.map(async (song) => {
          const track = await this.spotifyService.searchTrackDetails(
            accessToken,
            song.title,
            song.artist,
          );
          return { song, track };
        }),
      );

      for (const { song, track } of results) {
        if (track) {
          resolvedTracks.push(track);
        } else {
          notFound.push(`${song.title} by ${song.artist}`);
        }
      }
    }

    if (resolvedTracks.length === 0) {
      throw new HttpException(
        {
          error: PlaylistError.NO_TRACKS_RESOLVED,
          message: `None of the ${songs.length} songs were found on Spotify`,
        },
        HttpStatus.UNPROCESSABLE_ENTITY,
      );
    }

    const savedSongs = await this.songService.upsertSongsFromTracks(
      resolvedTracks.map((track) => ({
        title: track.title,
        artist: track.artist,
        spotifyUri: track.uri,
        spotifyUrl: track.url,
      })),
    );

    const unembedded = savedSongs.filter((song) => !song.embedding);
    if (unembedded.length > 0) {
      this.logger.log(
        `[generatePlaylist] Sending ${unembedded.length} resolved track(s) for embedding`,
      );
      const dtos = await this.dataEngineService.ingestBatch(
        unembedded.map((song) => ({
          title: song.name,
          artist: song.artistName,
        })),
      );
      await this.songService.updateEmbeddings(dtos);
    }

    const playlistTracks: PlaylistTrackResultDto[] = resolvedTracks.map(
      (track, index) => {
        const song = savedSongs[index];
        return {
          songId: song.id,
          title: song.name,
          artist: song.artistName,
          spotifyUri: track.uri,
          spotifyUrl: track.url,
          position: index + 1,
        };
      },
    );

    // 3. Create the playlist
    const playlistName =
      dto.playlistName || `JamOn: ${dto.eventDescription}`.slice(0, 100);
    const isPublic = true;
    const description = `Generated by JamOn for: ${dto.eventDescription}`;

    this.logger.log(
      `[generatePlaylist] Creating Spotify playlist: "${playlistName}"`,
    );
    const playlist = await this.spotifyService.createPlaylist(
      accessToken,
      playlistName,
      isPublic,
      description,
    );

    // 4. Add tracks
    this.logger.log(
      `[generatePlaylist] Adding ${resolvedTracks.length} tracks to playlist ${playlist.id}`,
    );
    await this.spotifyService.addTracksToPlaylist(
      accessToken,
      playlist.id,
      resolvedTracks.map((track) => track.uri),
    );

    this.logger.log(
      `[generatePlaylist] DONE — playlistId=${playlist.id}, url=${playlist.url}, added=${resolvedTracks.length}, notFound=${notFound.length}`,
    );
    return {
      playlistId: playlist.id,
      playlistUrl: playlist.url,
      tracksAdded: resolvedTracks.length,
      tracksNotFound: notFound,
      totalRequested: songs.length,
      tracks: playlistTracks,
    };
  }
}
