import { Injectable, Logger, HttpException, HttpStatus } from "@nestjs/common";
import { SpotifyService } from "../spotify/spotify.service";
import { DataEngineService } from "../data-engine/data-engine.service";
import {
  PlaylistResponseDto,
  PlaylistError,
} from "./dto/playlist-response.dto";
import { UserService } from "../user/user.service";
import { EventsService } from "../event/event.service";

@Injectable()
export class PlaylistService {
  private readonly logger = new Logger(PlaylistService.name);

  constructor(
    private readonly spotifyService: SpotifyService,
    private readonly dataEngineService: DataEngineService,
    private readonly userService: UserService,
    private readonly eventsService: EventsService,
  ) {}

  async generatePlaylist(
    eventId: string,
    userId: string,
  ): Promise<PlaylistResponseDto> {
    this.logger.log(
      `[generatePlaylist] START — eventId="${eventId}"`,
    );
    this.logger.log("[generatePlaylist] Calling data-engine /recommend...");
    const songs = await this.dataEngineService.getRecommendations(
      eventId
    );
    this.logger.log(
      `[generatePlaylist] Data-engine returned ${songs.length} recommendations`,
    );

    if (!songs.length) {
      throw new HttpException(
        {
          error: PlaylistError.NO_TRACKS_RESOLVED,
          message: "Data engine returned no recommendations",
        },
        HttpStatus.UNPROCESSABLE_ENTITY,
      );
    }

    // 2. Resolve each song to a Spotify URI (concurrency limit of 5)
    const resolvedUris: string[] = [];
    const notFound: string[] = [];

    const {spotifyAccessToken} = await this.userService.findById(userId) || {spotifyAccessToken: null};
    
    if (!spotifyAccessToken) {
      throw new HttpException(
        {
          error: PlaylistError.SPOTIFY_AUTH_EXPIRED,
          message: "User does not have a valid Spotify access token",
        },
        HttpStatus.UNAUTHORIZED,
      );
    }

    const chunks: (typeof songs)[] = [];
    for (let i = 0; i < songs.length; i += 5) {
      chunks.push(songs.slice(i, i + 5));
    }

    for (const chunk of chunks) {
      const results = await Promise.all(
        chunk.map(async (song) => {
          const uri = await this.spotifyService.searchTrack(
            spotifyAccessToken,
            song.title,
            song.artist,
          );
          return { song, uri };
        }),
      );

      for (const { song, uri } of results) {
        if (uri) {
          resolvedUris.push(uri);
        } else {
          notFound.push(`${song.title} by ${song.artist}`);
        }
      }
    }

    if (resolvedUris.length === 0) {
      throw new HttpException(
        {
          error: PlaylistError.NO_TRACKS_RESOLVED,
          message: `None of the ${songs.length} songs were found on Spotify`,
        },
        HttpStatus.UNPROCESSABLE_ENTITY,
      );
    }

    // 3. Create the playlist

    const {title, context} = await this.eventsService.findById(eventId, userId);

    const playlistName = title;
    const isPublic = true;
    const description = `Generated by JamOn for: ${context}`;
    this.logger.log(
      `[generatePlaylist] Creating Spotify playlist: "${playlistName}"`,
    );
    const playlist = await this.spotifyService.createPlaylist(
      spotifyAccessToken,
      playlistName,
      isPublic,
      description,
    );

    // 4. Add tracks
    this.logger.log(
      `[generatePlaylist] Adding ${resolvedUris.length} tracks to playlist ${playlist.id}`,
    );
    await this.spotifyService.addTracksToPlaylist(
      spotifyAccessToken,
      playlist.id,
      resolvedUris,
    );

    this.logger.log(
      `[generatePlaylist] DONE — playlistId=${playlist.id}, url=${playlist.url}, added=${resolvedUris.length}, notFound=${notFound.length}`,
    );
    return {
      playlistId: playlist.id,
      playlistUrl: playlist.url,
      tracksAdded: resolvedUris.length,
      tracksNotFound: notFound,
      totalRequested: songs.length,
    };
  }
}
