import { Injectable, Logger, HttpException, HttpStatus } from '@nestjs/common';
import { SpotifyService } from '../spotify/spotify.service';
import { DataEngineService } from '../data-engine/data-engine.service';
import { CreatePlaylistDto } from './dto/create-playlist.dto';
import { PlaylistResponseDto, PlaylistError } from './dto/playlist-response.dto';

@Injectable()
export class PlaylistService {
    private readonly logger = new Logger(PlaylistService.name);

    constructor(
        private readonly spotifyService: SpotifyService,
        private readonly dataEngineService: DataEngineService,
    ) {
    }

    async generatePlaylist(
        accessToken: string,
        dto: CreatePlaylistDto,
    ): Promise<PlaylistResponseDto> {
        const topTracks = await this.spotifyService.getTopTracks(accessToken, 15);
        const songs = await this.dataEngineService.getRecommendations(dto.eventDescription, topTracks);

        if (!songs.length) {
            throw new HttpException(
                {error: PlaylistError.NO_TRACKS_RESOLVED, message: 'Data engine returned no recommendations'},
                HttpStatus.UNPROCESSABLE_ENTITY,
            );
        }

        // 2. Resolve each song to a Spotify URI (concurrency limit of 5)
        const resolvedUris: string[] = [];
        const notFound: string[] = [];

        const chunks: typeof songs[] = [];
        for (let i = 0; i < songs.length; i += 5) {
            chunks.push(songs.slice(i, i + 5));
        }

        for (const chunk of chunks) {
            const results = await Promise.all(
                chunk.map(async (song) => {
                    const uri = await this.spotifyService.searchTrack(accessToken, song.title, song.artist);
                    return {song, uri};
                }),
            );

            for (const {song, uri} of results) {
                if (uri) {
                    resolvedUris.push(uri);
                } else {
                    notFound.push(`${song.title} by ${song.artist}`);
                }
            }
        }

        if (resolvedUris.length === 0) {
            throw new HttpException(
                {
                    error: PlaylistError.NO_TRACKS_RESOLVED,
                    message: `None of the ${songs.length} songs were found on Spotify`
                },
                HttpStatus.UNPROCESSABLE_ENTITY,
            );
        }

        // 3. Create the playlist
        const playlistName = dto.playlistName || `JamOn: ${dto.eventDescription}`.slice(0, 100);
        const isPublic = true;
        const description = `Generated by JamOn for: ${dto.eventDescription}`;

        const playlist = await this.spotifyService.createPlaylist(
            accessToken, playlistName, isPublic, description,
        );

        // 4. Add tracks
        await this.spotifyService.addTracksToPlaylist(accessToken, playlist.id, resolvedUris);

        return {
            playlistId: playlist.id,
            playlistUrl: playlist.url,
            tracksAdded: resolvedUris.length,
            tracksNotFound: notFound,
            totalRequested: songs.length,
        };
    }
}
