name: CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  placeholder:
    name: Pipeline not yet configured on main
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - run: echo "github sucks and this pipeline is not yet configured on main"